project:
  type: website
  output-dir: "."

website:
  favicon: favicon.ico
  title: "Wilkin Jones"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "About"
        href: about.qmd
      - text: "Resume"
        href: resume.qmd
  page-footer:
    center: "© 2025 Wilkin Jones"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    includes:
      in-header: includes/aos-header.html

execute:
  enabled: false

resources:
  - "*.html"