project:
  type: website

website:
  title: "Wilkin Jones"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "About"
        href: about.qmd
      - text: "Resume"
        href: resume.qmd
  page-footer:
    center: "© 2025 Wilkin Jones"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true

resources:
  - "*.html"